### ISSUE TITLE
Please release and add a version tag

### ISSUE THREAD

**Issue by archmoj** [go2garret/maps#1]
We want to load `arcgis_hybrid.json` in plotly.js source code
https://github.com/plotly/plotly.js/blob/34cade7e861435b4fbbb3005de72646008dc2754/src/plots/map/constants.js#L13
but to have stable results I prefer to load a version tag instead of a file that may possibly change in future.
Please let me know if you could possibly add a tag on your main branch?
If not we may use last commit hash.

Thank you @go2garret 

cc: @birkskyum @emilykl @ndrezn @gvwilson

**Comment by go2garret** [comment]
Greetings, I have released a stable version of the package here:

https://github.com/go2garret/maps/blob/v1.0.0/src/assets/json/arcgis_hybrid.json

Cheers :)

**Comment by archmoj** [comment]
Thanks @go2garret!
This is great for now.
I am wondering if you want to publish a npm package?
