### ISSUE TITLE
hybrid - missing "park" source layer

### ISSUE THREAD

**Issue by birkskyum** [go2garret/maps#2]
The "park" source layer is missing, which causes these two layers that depend on it to fail:

park-outline
landcover-grass-park

If the park layer can be added it would be nice, but otherwise it's better to remove the dependent layers than have them crash.

A style with the problematic layers removed can be found here:
- https://github.com/plotly/plotly.js/blob/e939d1062287894181177919c414d2efde6a5a60/src/plots/map/styles/arcgis-sat-hybrid.json

**Comment by go2garret** [comment]
Hello, I have removed the missing source and published release. Sorry for the delay!
